version: '3'

services:
  broker_service:
    build:
      context: .
      dockerfile: dockerfile
    image: backend:1.0
    expose:
      - 3000
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - brokernet

networks:
  brokernet: