version: '3'

services:
  broker_service:
    build:
      context: .
      dockerfile: dockerfile
    image: backend:1.0
    expose:
      - 3000
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - brokernet

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=qa
      - MYSQL_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - brokernet     

networks:
  brokernet: