services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: qa
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
      MYSQL_ROOT_HOST: '%'
    networks:
      - internalnet

  backend_service:
    build:
      context: .
      dockerfile: dockerfile
    image: backend:1.0
    expose:
      - 3000
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge